/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TBSettingsJPanel.java
 *
 * Created on 2011-07-30, 23:22:12
 */
package stk.timebalance;

import stk.Main;

/**
 *
 * @author user
 */
public class TBSettingsJPanel extends javax.swing.JPanel {

    /** Creates new form TBSettingsJPanel */
    public TBSettingsJPanel() {
        initComponents();
        loadSettings();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_TW = new javax.swing.JCheckBox();
        CB_LW = new javax.swing.JCheckBox();
        CB_TM = new javax.swing.JCheckBox();
        CB_LM = new javax.swing.JCheckBox();
        CB_T = new javax.swing.JCheckBox();
        CB_LWD = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        CB_LR = new javax.swing.JCheckBox();

        CB_TW.setText("This week");
        CB_TW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TWActionPerformed(evt);
            }
        });

        CB_LW.setText("Last week");
        CB_LW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_LWActionPerformed(evt);
            }
        });

        CB_TM.setText("This month");
        CB_TM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TMActionPerformed(evt);
            }
        });

        CB_LM.setText("Last month");
        CB_LM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_LMActionPerformed(evt);
            }
        });

        CB_T.setText("Today");
        CB_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TActionPerformed(evt);
            }
        });

        CB_LWD.setText("Last working day");
        CB_LWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_LWDActionPerformed(evt);
            }
        });

        jLabel1.setText("Make selection");

        CB_LR.setText("Last run");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_TW)
                            .addComponent(CB_LW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_TM)
                            .addComponent(CB_LM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CB_T)
                                .addGap(18, 18, 18)
                                .addComponent(CB_LR))
                            .addComponent(CB_LWD)))
                    .addComponent(jLabel1))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB_T)
                            .addComponent(CB_LR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_LWD))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CB_TM)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CB_LM))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CB_TW)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CB_LW))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CB_TWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_TWActionPerformed

    private void CB_LWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_LWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_LWActionPerformed

    private void CB_TMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_TMActionPerformed

    private void CB_LMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_LMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_LMActionPerformed

    private void CB_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_TActionPerformed

    private void CB_LWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_LWDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_LWDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB_LM;
    private javax.swing.JCheckBox CB_LR;
    private javax.swing.JCheckBox CB_LW;
    private javax.swing.JCheckBox CB_LWD;
    private javax.swing.JCheckBox CB_T;
    private javax.swing.JCheckBox CB_TM;
    private javax.swing.JCheckBox CB_TW;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    void undoChanges() {
        loadSettings();
    }

    void commitChanges() {
        Main main = Main.getInstance();
        main.setProperty("CB_TW_selection", CB_TW.isSelected());
        main.setProperty("CB_LW_selection", CB_LW.isSelected());
        main.setProperty("CB_TM_selection", CB_TM.isSelected());
        main.setProperty("CB_LM_selection", CB_LM.isSelected());
        main.setProperty("CB_T_selection", CB_T.isSelected());
        main.setProperty("CB_LWD_selection", CB_LWD.isSelected());
        main.setProperty("CB_LR_selection", CB_LR.isSelected());
    }

    private void loadSettings() {
        Main main = Main.getInstance();
        CB_TW.setSelected((Boolean)main.getProperty("CB_TW_selection", Boolean.FALSE));
        CB_LW.setSelected((Boolean)main.getProperty("CB_LW_selection", Boolean.FALSE));
        CB_TM.setSelected((Boolean)main.getProperty("CB_TM_selection", Boolean.FALSE));
        CB_LM.setSelected((Boolean)main.getProperty("CB_LM_selection", Boolean.FALSE));
        CB_T.setSelected((Boolean)main.getProperty("CB_T_selection", Boolean.FALSE));
        CB_LWD.setSelected((Boolean)main.getProperty("CB_LWD_selection", Boolean.FALSE));
        CB_LR.setSelected((Boolean)main.getProperty("CB_LR_selection", Boolean.TRUE)); 
    }

    /**
     * @return the CB_LM
     */
    public javax.swing.JCheckBox getCB_LM() {
        return CB_LM;
    }

    /**
     * @return the CB_LR
     */
    public javax.swing.JCheckBox getCB_LR() {
        return CB_LR;
    }

    /**
     * @return the CB_LW
     */
    public javax.swing.JCheckBox getCB_LW() {
        return CB_LW;
    }

    /**
     * @return the CB_LWD
     */
    public javax.swing.JCheckBox getCB_LWD() {
        return CB_LWD;
    }

    /**
     * @return the CB_T
     */
    public javax.swing.JCheckBox getCB_T() {
        return CB_T;
    }

    /**
     * @return the CB_TM
     */
    public javax.swing.JCheckBox getCB_TM() {
        return CB_TM;
    }

    /**
     * @return the CB_TW
     */
    public javax.swing.JCheckBox getCB_TW() {
        return CB_TW;
    }
}
